#!/usr/bin/env php
<?php

use Slonyaka\OpencartCli\Core\Kernel;
use Slonyaka\OpencartCli\Core\Request;

require_once 'vendor/autoload.php';

$request = new Request($argv);
$kernel = new Kernel($request);

$kernel->handle();