#!/usr/bin/env php
<?php

/**
 * Opencart version 3.*
 */

use Slonyaka\OpencartCli\Core\ConsoleRequest;
use Slonyaka\OpencartCli\Core\Kernel;
use Slonyaka\OpencartCli\Core\Request;

require_once 'vendor/autoload.php';

const OC_CLI_ROOT = __DIR__ . '/';

try {
    $app = app();
    $app->add(ConsoleRequest::class, new Request($argv));
    /**
     * @var Kernel $kernel
     */
    $kernel = $app->get(Kernel::class);
    $output = $kernel->handle();
    $output->print();
} catch (Exception $e) {
    echo basename(get_class($e)) . ': ' . $e->getMessage();
    exit;
}

